export const LESSONS = [
  // ── BEGINNER ──────────────────────────────────────────────────────────────
  {
    id: 'budget-101',
    category: 'Budgeting',
    difficulty: 'beginner',
    emoji: '💰',
    title: 'The 50/30/20 Rule',
    description: 'The simplest budgeting system ever created',
    xp: 10,
    content: 'The 50/30/20 rule splits your income into three buckets: 50% for needs (rent, food, bills), 30% for wants (eating out, subscriptions, fun), and 20% for savings and debt payoff. It\'s the starter pack of personal finance.',
    questions: [
      { q: 'In the 50/30/20 rule, what percentage goes to "needs"?', options: ['20%', '30%', '50%', '40%'], correct: 2 },
      { q: 'Which of these is a "want" in the 50/30/20 rule?', options: ['Rent', 'Netflix subscription', 'Groceries', 'Electric bill'], correct: 1 },
      { q: 'What does the "20" in 50/30/20 represent?', options: ['Fun money', 'Food budget', 'Savings & debt', 'Transport'], correct: 2 },
      { q: 'If you make $3,000/month, how much goes to savings?', options: ['$300', '$600', '$900', '$1,500'], correct: 1 },
    ],
  },
  {
    id: 'credit-score-101',
    category: 'Credit',
    difficulty: 'beginner',
    emoji: '📊',
    title: 'Credit Scores 101',
    description: 'What is a credit score and why does it matter?',
    xp: 10,
    content: 'A credit score (300–850) is a number that tells lenders how likely you are to pay back money. The higher the number, the better. It affects your ability to get apartments, car loans, and even some jobs. Payment history is the biggest factor — always pay on time.',
    questions: [
      { q: 'What is the range of a FICO credit score?', options: ['0–100', '300–850', '500–1000', '1–10'], correct: 1 },
      { q: 'What is the MOST important factor in your credit score?', options: ['Credit age', 'Number of cards', 'Payment history', 'Income'], correct: 2 },
      { q: 'A score of 750 is considered:', options: ['Poor', 'Fair', 'Good', 'Excellent'], correct: 3 },
      { q: 'Which action HURTS your credit score?', options: ['Paying bills on time', 'Missing a payment', 'Keeping old accounts open', 'Low credit utilization'], correct: 1 },
    ],
  },
  {
    id: 'compound-interest',
    category: 'Investing',
    difficulty: 'beginner',
    emoji: '🚀',
    title: 'Compound Interest',
    description: 'The 8th wonder of the world — Einstein said so',
    xp: 10,
    content: 'Compound interest means you earn interest on your interest. If you invest $1,000 at 7% per year, after year 1 you have $1,070. Year 2: $1,144.90. The money grows exponentially over time — this is why starting early is literally worth thousands of dollars.',
    questions: [
      { q: 'Compound interest means you earn interest on:', options: ['Your salary only', 'Your initial deposit only', 'Your interest too', 'Other people\'s money'], correct: 2 },
      { q: '$1,000 at 10% simple interest for 2 years = ?', options: ['$1,100', '$1,200', '$1,210', '$2,000'], correct: 1 },
      { q: 'Why is starting to invest early so powerful?', options: ['Stocks are cheaper when young', 'More time for compounding', 'Banks give better rates', 'Tax benefits'], correct: 1 },
      { q: 'What is the "Rule of 72"?', options: ['Divide 72 by interest rate to find doubling time', 'Save 72% of income', 'Never spend more than $72/day', 'Work 72 hours to retire'], correct: 0 },
    ],
  },
  {
    id: 'emergency-fund',
    category: 'Budgeting',
    difficulty: 'beginner',
    emoji: '🛡️',
    title: 'Emergency Fund',
    description: 'Your financial safety net — build it first',
    xp: 10,
    content: 'An emergency fund is 3–6 months of living expenses saved in a high-yield savings account (HYSA). It\'s for real emergencies: job loss, medical bills, car repairs. Without it, unexpected costs go on credit cards and create debt spirals.',
    questions: [
      { q: 'How many months of expenses should an emergency fund cover?', options: ['1–2 months', '3–6 months', '10–12 months', '2 years'], correct: 1 },
      { q: 'Where should you keep your emergency fund?', options: ['In stocks', 'Under your mattress', 'High-yield savings account', 'In crypto'], correct: 2 },
      { q: 'Which of these is a legitimate emergency fund use?', options: ['Concert tickets', 'New iPhone', 'Car engine breaks down', 'Vacation flights'], correct: 2 },
      { q: 'What happens if you invest your emergency fund in stocks?', options: ['It grows faster', 'You might need to sell at a loss', 'Banks give bonuses', 'Nothing changes'], correct: 1 },
    ],
  },
  {
    id: 'debit-vs-credit',
    category: 'Credit',
    difficulty: 'beginner',
    emoji: '💳',
    title: 'Debit vs Credit Cards',
    description: 'They look the same but work very differently',
    xp: 10,
    content: 'Debit cards pull money directly from your bank account. Credit cards let you borrow money from the card company and pay it back monthly. Credit cards build your credit score, offer fraud protection, and often have rewards — but only if you pay the full balance every month.',
    questions: [
      { q: 'A debit card pulls money from:', options: ['A loan', 'Your bank account', 'The government', 'Your credit score'], correct: 1 },
      { q: 'Credit cards are best used when:', options: ['You pay the full balance monthly', 'You only pay minimums', 'You carry a balance', 'You max it out'], correct: 0 },
      { q: 'Which offers better fraud protection?', options: ['Debit card', 'Cash', 'Credit card', 'Both are equal'], correct: 2 },
      { q: 'Using a credit card responsibly can:', options: ['Hurt your credit score', 'Build your credit score', 'Empty your bank account', 'Increase your income'], correct: 1 },
    ],
  },

  // ── INTERMEDIATE ──────────────────────────────────────────────────────────
  {
    id: 'etfs-explained',
    category: 'Investing',
    difficulty: 'intermediate',
    emoji: '📦',
    title: 'ETFs Explained',
    description: 'The lazy investor\'s best friend',
    xp: 20,
    content: 'An ETF (Exchange-Traded Fund) is a basket of stocks you can buy in one shot. Instead of picking individual stocks, you buy a fund that tracks an index like the S&P 500. ETFs are diversified, low-cost, and historically beat 90% of actively managed funds over time.',
    questions: [
      { q: 'ETF stands for:', options: ['Every Trading Fund', 'Exchange-Traded Fund', 'Equity Transfer Fee', 'External Trade Finance'], correct: 1 },
      { q: 'What does the S&P 500 ETF track?', options: ['500 crypto coins', '500 largest US companies', '500 government bonds', '500 real estate properties'], correct: 1 },
      { q: 'Why are ETFs good for beginners?', options: ['They guarantee profits', 'They are diversified and low-cost', 'They have no risk', 'Banks force you to buy them'], correct: 1 },
      { q: 'ETFs vs mutual funds — ETFs are usually:', options: ['More expensive', 'Less diversified', 'Lower cost and more flexible', 'Only for rich investors'], correct: 2 },
    ],
  },
  {
    id: 'roth-ira',
    category: 'Investing',
    difficulty: 'intermediate',
    emoji: '🏦',
    title: 'Roth IRA vs Traditional IRA',
    description: 'Tax-advantaged retirement accounts explained',
    xp: 20,
    content: 'A Roth IRA lets you invest after-tax money and withdraw it TAX-FREE in retirement. A Traditional IRA lets you invest pre-tax money (lowering taxes now) but you pay taxes when you withdraw. For most young people, Roth wins because you\'re in a lower tax bracket now.',
    questions: [
      { q: 'Roth IRA contributions are made with:', options: ['Pre-tax money', 'After-tax money', 'Employer money', 'Government grants'], correct: 1 },
      { q: 'When do you pay taxes on a Roth IRA?', options: ['When you contribute', 'When you withdraw', 'Never', 'Every year'], correct: 2 },
      { q: 'For most young people, which is better?', options: ['Traditional IRA', 'Roth IRA', 'Neither', 'Both are exactly equal'], correct: 1 },
      { q: 'What is the 2024 Roth IRA contribution limit?', options: ['$3,000', '$5,000', '$7,000', '$20,000'], correct: 2 },
    ],
  },
  {
    id: 'anchoring-bias',
    category: 'Psychology',
    difficulty: 'intermediate',
    emoji: '⚓',
    title: 'Anchoring Bias',
    description: 'Why the first number you see changes everything',
    xp: 20,
    content: 'Anchoring bias is when your brain gets "anchored" to the first number it sees and uses it as a reference point for all future decisions. A $200 shirt seems cheap after seeing a $500 one. Stores use this constantly — "Was $100, now $60" makes $60 feel like a deal even if it\'s overpriced.',
    questions: [
      { q: 'Anchoring bias means you are influenced by:', options: ['Your friends\' opinions', 'The first number you see', 'Your salary', 'Past purchases'], correct: 1 },
      { q: '"Was $500, NOW $200" is an example of:', options: ['Honest pricing', 'Anchoring manipulation', 'Compound interest', 'Dollar-cost averaging'], correct: 1 },
      { q: 'How can you fight anchoring bias?', options: ['Research real market prices independently', 'Trust the sale price', 'Always buy the cheapest option', 'Ignore all prices'], correct: 0 },
      { q: 'Which industry most commonly uses anchoring?', options: ['Agriculture', 'Retail / marketing', 'Construction', 'Farming'], correct: 1 },
    ],
  },
  {
    id: 'dollar-cost-averaging',
    category: 'Investing',
    difficulty: 'intermediate',
    emoji: '📅',
    title: 'Dollar-Cost Averaging',
    description: 'The strategy that beats trying to time the market',
    xp: 20,
    content: 'Dollar-cost averaging (DCA) means investing a fixed amount of money at regular intervals regardless of the market. Instead of trying to buy at the "perfect" time, you buy consistently. Over time, you buy more shares when prices are low and fewer when high — averaging out your cost.',
    questions: [
      { q: 'Dollar-cost averaging means:', options: ['Buying at the lowest price', 'Investing a fixed amount regularly', 'Only buying in bull markets', 'Averaging your spending'], correct: 1 },
      { q: 'DCA helps you avoid:', options: ['All investment losses', 'Trying to time the market', 'Paying taxes', 'Market volatility entirely'], correct: 1 },
      { q: 'When prices drop with DCA, you:', options: ['Panic and sell', 'Buy more shares for the same money', 'Stop investing', 'Withdraw funds'], correct: 1 },
      { q: 'DCA works best for:', options: ['Day traders', 'Long-term investors', 'Short-term speculation', 'Real estate only'], correct: 1 },
    ],
  },
  {
    id: 'credit-unions',
    category: 'Credit',
    difficulty: 'intermediate',
    emoji: '🤝',
    title: 'Credit Unions vs Banks',
    description: 'The secret banks don\'t want you to know about',
    xp: 20,
    content: 'Credit unions are nonprofit financial cooperatives owned by their members. Because they don\'t have shareholders to pay, they offer lower loan rates, higher savings rates, and lower fees than traditional banks. The downside: fewer ATMs and locations, and you must qualify to join.',
    questions: [
      { q: 'Credit unions are owned by:', options: ['Wall Street investors', 'The government', 'Their members', 'Private corporations'], correct: 2 },
      { q: 'Why do credit unions offer better rates?', options: ['They take more risk', 'They are nonprofits with no shareholders', 'They have more money', 'Government subsidies'], correct: 1 },
      { q: 'What is a downside of credit unions?', options: ['Higher fees', 'Fewer locations and ATMs', 'No savings accounts', 'Government owned'], correct: 1 },
      { q: 'Credit union deposits are insured by:', options: ['FDIC', 'NCUA', 'The Federal Reserve', 'Private insurance only'], correct: 1 },
    ],
  },

  // ── ADVANCED ──────────────────────────────────────────────────────────────
  {
    id: 'behavioral-finance',
    category: 'Psychology',
    difficulty: 'advanced',
    emoji: '🧠',
    title: 'Behavioral Finance Biases',
    description: 'Why smart people make dumb money decisions',
    xp: 30,
    content: 'Behavioral finance studies how psychology affects financial decisions. Key biases: Loss aversion (losses feel 2x worse than gains), FOMO investing (buying when others are), sunk cost fallacy (holding bad investments because you already lost money), and recency bias (assuming recent trends continue forever).',
    questions: [
      { q: 'Loss aversion means losses feel how much worse than equivalent gains?', options: ['Same amount', '1.5x worse', '2x worse', '5x worse'], correct: 2 },
      { q: 'Buying a stock because everyone else is is called:', options: ['Smart investing', 'Herd mentality / FOMO', 'Dollar-cost averaging', 'Value investing'], correct: 1 },
      { q: 'Holding a losing stock because "I\'ve already lost too much to sell" is:', options: ['Good strategy', 'Value investing', 'Sunk cost fallacy', 'Tax-loss harvesting'], correct: 2 },
      { q: 'Recency bias means you assume:', options: ['Old trends repeat', 'Recent trends continue forever', 'Past returns predict future', 'Markets always go up'], correct: 1 },
    ],
  },
  {
    id: 'tax-loss-harvesting',
    category: 'Investing',
    difficulty: 'advanced',
    emoji: '🌾',
    title: 'Tax-Loss Harvesting',
    description: 'Turn your losses into a tax advantage',
    xp: 30,
    content: 'Tax-loss harvesting means selling investments at a loss to offset capital gains taxes. If you made $10,000 profit on one stock and lost $4,000 on another, you only pay taxes on $6,000 net. You can then reinvest in a similar (not identical) asset. This is a legal, powerful strategy used by wealthy investors.',
    questions: [
      { q: 'Tax-loss harvesting involves:', options: ['Selling winners', 'Selling losers to offset gains', 'Buying at a loss', 'Avoiding all taxes'], correct: 1 },
      { q: 'If you gain $10K and harvest $3K loss, you pay taxes on:', options: ['$10,000', '$13,000', '$7,000', '$3,000'], correct: 2 },
      { q: 'The "wash sale rule" says you cannot:', options: ['Sell at a loss', 'Buy back the same stock within 30 days', 'Invest in ETFs', 'Use a Roth IRA'], correct: 1 },
      { q: 'Tax-loss harvesting is most useful when:', options: ['You have no gains', 'You have significant capital gains', 'Markets are rising', 'You are in a low tax bracket'], correct: 1 },
    ],
  },
  {
    id: 'portfolio-diversification',
    category: 'Investing',
    difficulty: 'advanced',
    emoji: '🎯',
    title: 'Portfolio Diversification',
    description: 'Don\'t put all your eggs in one basket',
    xp: 30,
    content: 'Diversification spreads investments across different assets, sectors, and geographies to reduce risk. A diversified portfolio might include US stocks, international stocks, bonds, and REITs. The key insight: assets that move in opposite directions (negative correlation) reduce your overall portfolio volatility.',
    questions: [
      { q: 'The main goal of diversification is to:', options: ['Maximize returns', 'Reduce risk', 'Pick winning stocks', 'Avoid taxes'], correct: 1 },
      { q: 'Which portfolio is MORE diversified?', options: ['10 tech stocks', '1 S&P 500 ETF + 1 bond ETF', 'All Apple shares', '5 crypto coins'], correct: 1 },
      { q: 'Negative correlation between assets means:', options: ['Both always go up', 'They move in opposite directions', 'Both always go down', 'They have no relationship'], correct: 1 },
      { q: 'Owning only US stocks means you lack:', options: ['Sector diversification', 'Geographic diversification', 'Asset class diversity', 'All of the above'], correct: 3 },
    ],
  },
  {
    id: 'options-basics',
    category: 'Investing',
    difficulty: 'advanced',
    emoji: '⚡',
    title: 'Options Basics',
    description: 'High risk, high reward — understand before you trade',
    xp: 30,
    content: 'Options are contracts giving you the right (not obligation) to buy or sell a stock at a set price before a date. A "call" option bets the price goes up. A "put" option bets it goes down. Options can multiply gains — but you can lose 100% of what you put in. They are NOT for beginners.',
    questions: [
      { q: 'A "call" option profits when the stock price:', options: ['Goes down', 'Stays flat', 'Goes up', 'Is deleted'], correct: 2 },
      { q: 'A "put" option is a bet that the price will:', options: ['Go up', 'Go down', 'Stay the same', 'Double'], correct: 1 },
      { q: 'What is the maximum loss when buying an option?', options: ['Unlimited', 'The premium paid', 'The stock price', 'Zero'], correct: 1 },
      { q: 'Options are recommended for:', options: ['Complete beginners', 'Anyone with a brokerage', 'Experienced investors who understand the risk', 'People looking for guaranteed returns'], correct: 2 },
    ],
  },
  {
    id: 'inflation',
    category: 'Economics',
    difficulty: 'advanced',
    emoji: '📉',
    title: 'Inflation & Purchasing Power',
    description: 'Why keeping cash is actually losing money',
    xp: 30,
    content: 'Inflation is the rate at which prices rise over time. At 3% annual inflation, $100 today buys what $97 buys next year. Cash sitting in a 0.01% savings account loses purchasing power every year. This is why investing — even in boring index funds — is necessary to stay ahead of inflation.',
    questions: [
      { q: 'Inflation means your money\'s purchasing power:', options: ['Increases', 'Stays the same', 'Decreases', 'Doubles'], correct: 2 },
      { q: 'At 3% inflation, $1,000 today is worth what in a year?', options: ['$1,030', '$970', '$1,000', '$930'], correct: 1 },
      { q: 'To beat inflation, your investments must return:', options: ['0%', 'Less than inflation', 'More than inflation', 'Exactly inflation'], correct: 2 },
      { q: 'Which historically beats inflation over long periods?', options: ['Cash under the mattress', 'A 0.01% savings account', 'Broad stock market index funds', 'Lottery tickets'], correct: 2 },
    ],
  },
];

export const CATEGORIES = ['All', 'Budgeting', 'Credit', 'Investing', 'Psychology', 'Economics'];
export const DIFFICULTIES = ['all', 'beginner', 'intermediate', 'advanced'];
