// World 1: Money Basics  |  World 2: Credit & Debt

export const WORLD1_LESSONS = [
  {
    id: 'budget-101', category: 'Budgeting', difficulty: 'beginner', emoji: '💰',
    title: 'The 50/30/20 Rule', xp: 10,
    description: 'The simplest budgeting system ever created',
    content: 'The 50/30/20 rule splits your income into three buckets: 50% for needs (rent, food, bills), 30% for wants (eating out, subscriptions, fun), and 20% for savings and debt payoff. It\'s the starter pack of personal finance.',
    questions: [
      { q: 'In the 50/30/20 rule, what % goes to needs?', options: ['20%','30%','50%','40%'], correct: 2 },
      { q: 'Which is a "want" in the 50/30/20 rule?', options: ['Rent','Netflix subscription','Groceries','Electric bill'], correct: 1 },
      { q: 'What does the "20" represent?', options: ['Fun money','Food budget','Savings & debt','Transport'], correct: 2 },
      { q: 'If you earn $3,000/month, savings = ?', options: ['$300','$600','$900','$1,500'], correct: 1 },
      { q: 'Which category does a gym membership fall under?', options: ['Needs','Wants','Savings','Debt'], correct: 1 },
    ],
  },
  {
    id: 'credit-score-101', category: 'Credit', difficulty: 'beginner', emoji: '📊',
    title: 'Credit Scores 101', xp: 10,
    description: 'What is a credit score and why does it matter?',
    content: 'A credit score (300–850) tells lenders how likely you are to repay money. Higher is better. It affects apartments, car loans, and even some jobs. Payment history is the biggest factor — always pay on time.',
    questions: [
      { q: 'FICO credit score range is:', options: ['0–100','300–850','500–1000','1–10'], correct: 1 },
      { q: 'Most important credit score factor?', options: ['Credit age','Number of cards','Payment history','Income'], correct: 2 },
      { q: 'A score of 750 is considered:', options: ['Poor','Fair','Good','Excellent'], correct: 3 },
      { q: 'Which action HURTS your score?', options: ['Paying on time','Missing a payment','Keeping old accounts','Low utilization'], correct: 1 },
      { q: 'Credit utilization should stay below:', options: ['80%','60%','30%','10%'], correct: 2 },
    ],
  },
  {
    id: 'compound-interest', category: 'Investing', difficulty: 'beginner', emoji: '🚀',
    title: 'Compound Interest', xp: 10,
    description: 'The 8th wonder of the world — Einstein said so',
    content: 'Compound interest means you earn interest on your interest. $1,000 at 7% per year → $1,070 after year 1 → $1,144.90 after year 2. The money grows exponentially — starting early is literally worth thousands of dollars.',
    questions: [
      { q: 'Compound interest = earning interest on:', options: ['Salary only','Initial deposit only','Your interest too','Others\' money'], correct: 2 },
      { q: '$1,000 at 10% simple interest for 2 years = ?', options: ['$1,100','$1,200','$1,210','$2,000'], correct: 1 },
      { q: 'Why is starting to invest early powerful?', options: ['Cheaper stocks','More compounding time','Better bank rates','Tax benefits'], correct: 1 },
      { q: 'Rule of 72: divide 72 by the interest rate to get:', options: ['Monthly return','Years to double money','Tax owed','Break-even point'], correct: 1 },
      { q: '$500 at 6% for 10 years with compounding ≈ ?', options: ['$800','$895','$1,200','$1,500'], correct: 1 },
    ],
  },
  {
    id: 'emergency-fund', category: 'Budgeting', difficulty: 'beginner', emoji: '🛡️',
    title: 'Emergency Fund', xp: 10,
    description: 'Your financial safety net — build it first',
    content: 'An emergency fund = 3–6 months of living expenses in a high-yield savings account. It\'s for real emergencies: job loss, medical bills, car repairs. Without it, unexpected costs go on credit cards and create debt spirals.',
    questions: [
      { q: 'Emergency fund should cover how many months?', options: ['1–2','3–6','10–12','2 years'], correct: 1 },
      { q: 'Best place to keep your emergency fund?', options: ['Stocks','Mattress','High-yield savings','Crypto'], correct: 2 },
      { q: 'A legit emergency fund use:', options: ['Concert tickets','New iPhone','Broken car engine','Vacation'], correct: 2 },
      { q: 'Investing your emergency fund in stocks risks:', options: ['Faster growth','Selling at a loss in a crisis','Bank bonuses','Nothing'], correct: 1 },
      { q: 'What happens if you use your emergency fund?', options: ['You lose the money','Rebuild it ASAP','Pay a penalty','Cancel all subscriptions'], correct: 1 },
    ],
  },
  {
    id: 'debit-vs-credit', category: 'Credit', difficulty: 'beginner', emoji: '💳',
    title: 'Debit vs Credit Cards', xp: 10,
    description: 'They look the same but work very differently',
    content: 'Debit cards pull money directly from your bank account. Credit cards let you borrow from the card company and pay back monthly. Credit cards build your score, offer fraud protection, and have rewards — but only if you pay the full balance monthly.',
    questions: [
      { q: 'Debit card pulls money from:', options: ['A loan','Your bank account','The government','Your credit score'], correct: 1 },
      { q: 'Credit cards are best when:', options: ['You pay full balance monthly','You pay minimums','You carry a balance','You max it out'], correct: 0 },
      { q: 'Better fraud protection?', options: ['Debit','Cash','Credit card','Both equal'], correct: 2 },
      { q: 'Responsible credit card use can:', options: ['Hurt score','Build score','Empty bank account','Increase income'], correct: 1 },
      { q: 'If you carry a credit card balance, you pay:', options: ['No extra cost','Interest charges','Annual fee only','Government tax'], correct: 1 },
    ],
  },
  {
    id: 'needs-vs-wants', category: 'Budgeting', difficulty: 'beginner', emoji: '🧾',
    title: 'Needs vs Wants', xp: 10,
    description: 'The first step to any budget is knowing the difference',
    content: 'Needs are things you must have to survive and function: rent, groceries, utilities, transportation to work. Wants are everything else. The line can blur — a smartphone is a want, but a basic phone for work calls might be a need. Being honest with yourself here is the foundation of any budget.',
    questions: [
      { q: 'Which is a NEED?', options: ['Concert tickets','Monthly rent','New Air Jordans','Spotify'], correct: 1 },
      { q: 'Which is a WANT?', options: ['Electricity bill','Work uniform','Gym membership','Groceries'], correct: 2 },
      { q: 'Why distinguish needs from wants?', options: ['To impress others','To prioritize spending','To avoid taxes','To get credit'], correct: 1 },
      { q: 'A smartphone is usually classified as:', options: ['A need','A want','A saving','An asset'], correct: 1 },
      { q: 'What should you fund first in a budget?', options: ['Wants','Needs + savings','Entertainment','Investments'], correct: 1 },
    ],
  },
  {
    id: 'pay-yourself-first', category: 'Budgeting', difficulty: 'beginner', emoji: '🥇',
    title: 'Pay Yourself First', xp: 10,
    description: 'The secret habit of people who actually save money',
    content: 'Pay yourself first means automatically moving money to savings the moment you get paid — before you spend anything. Instead of saving "what\'s left," you save first and spend what remains. Automating this is the single most effective savings habit you can build.',
    questions: [
      { q: '"Pay yourself first" means:', options: ['Buy yourself gifts','Save before spending','Quit your job','Invest in luxury'], correct: 1 },
      { q: 'Best way to pay yourself first:', options: ['Manually transfer weekly','Automate it on payday','Wait till month end','Ask a friend'], correct: 1 },
      { q: 'This strategy works because:', options: ['Banks reward it','You spend what\'s left, not save what\'s left','It avoids taxes','It beats inflation'], correct: 1 },
      { q: 'Where should "pay yourself first" money go?', options: ['Checking account','Savings/investment account','Wallet','Cash jar'], correct: 1 },
      { q: 'Even saving $25/paycheck beats:', options: ['Investing in crypto','Saving nothing','Carrying a balance','Spending on wants'], correct: 1 },
    ],
  },
  {
    id: 'spending-triggers', category: 'Psychology', difficulty: 'beginner', emoji: '🎯',
    title: 'Spending Triggers', xp: 10,
    description: 'Why you buy stuff you don\'t need',
    content: 'Spending triggers are emotional or situational cues that push you to spend impulsively. Common ones: boredom, stress, social media scrolling, sales notifications, peer pressure, and "treat yourself" mentality. Recognizing your triggers is the first step to controlling them.',
    questions: [
      { q: 'A spending trigger is:', options: ['A credit card limit','An emotional cue to spend','A budget category','A bank fee'], correct: 1 },
      { q: 'Which is a common emotional trigger?', options: ['Paying bills','Stress shopping','Reading bank statements','Saving automatically'], correct: 1 },
      { q: 'Best response to an impulse buy urge:', options: ['Buy immediately','Wait 24 hours','Use a credit card','Tell your friends'], correct: 1 },
      { q: 'Social media can trigger spending by:', options: ['Teaching budgeting','Showing products and lifestyles','Blocking purchases','Hiding prices'], correct: 1 },
      { q: 'How do you break a spending trigger habit?', options: ['Ignore it','Identify, pause, and redirect','Spend more to feel better','Cut all cards'], correct: 1 },
    ],
  },
  {
    id: 'financial-goals', category: 'Budgeting', difficulty: 'beginner', emoji: '🎯',
    title: 'Setting Financial Goals', xp: 10,
    description: 'Goals without a plan are just wishes',
    content: 'Financial goals work best when they are SMART: Specific, Measurable, Achievable, Relevant, Time-bound. "I want to save money" fails. "I will save $2,000 for a trip by December by putting $250/month aside" works. Short-term goals (<1yr), mid-term (1–5yr), and long-term (5yr+) each need different strategies.',
    questions: [
      { q: 'SMART goals are:', options: ['Simple, Manageable, Accurate, Rich, Timely','Specific, Measurable, Achievable, Relevant, Time-bound','Safe, Modern, Agile, Real, Transferable','None of these'], correct: 1 },
      { q: 'A short-term financial goal has a timeline of:', options: ['10+ years','5–10 years','1–5 years','Under 1 year'], correct: 3 },
      { q: 'Which is a SMART goal?', options: ['Save more money','Spend less','Save $500 in 4 months for an emergency fund','Never eat out'], correct: 2 },
      { q: 'Long-term goals (5+ years) are best funded with:', options: ['Checking account','Cash under a mattress','Investments that grow','Weekly poker'], correct: 2 },
      { q: 'Why write down financial goals?', options: ['Banks require it','Increases commitment and tracking','It earns interest','Required by law'], correct: 1 },
    ],
  },
  {
    id: 'bank-accounts', category: 'Banking', difficulty: 'beginner', emoji: '🏦',
    title: 'Types of Bank Accounts', xp: 10,
    description: 'Knowing which account to use saves you money',
    content: 'Checking accounts are for daily spending — pay bills, buy groceries, use your debit card. Savings accounts are for storing money you don\'t need immediately. High-yield savings accounts (HYSAs) earn more interest than traditional savings. Money market accounts blend both. Each has different rules and purposes.',
    questions: [
      { q: 'Checking accounts are best for:', options: ['Long-term savings','Daily spending','Investing','Emergency funds'], correct: 1 },
      { q: 'A high-yield savings account offers:', options: ['Higher risk','Higher interest rates','Free stocks','Lower FDIC protection'], correct: 1 },
      { q: 'FDIC insurance protects up to how much per bank?', options: ['$50,000','$100,000','$250,000','$1,000,000'], correct: 2 },
      { q: 'Money market accounts typically offer:', options: ['Stock market returns','Higher rates + limited check writing','No interest','Crypto storage'], correct: 1 },
      { q: 'Best account for a 6-month emergency fund?', options: ['Checking','Investment brokerage','High-yield savings','Crypto wallet'], correct: 2 },
    ],
  },
  {
    id: 'saving-habits', category: 'Budgeting', difficulty: 'beginner', emoji: '🌟',
    title: 'Building Saving Habits', xp: 10,
    description: 'Small consistent actions beat big one-time efforts',
    content: 'Saving consistently is a habit, not a one-time event. Key strategies: automate transfers on payday, start small (even $10/week), use separate savings accounts for each goal, track your progress, and celebrate milestones. Habits compound just like interest — the earlier you start, the easier it gets.',
    questions: [
      { q: 'Best way to build a saving habit:', options: ['Save whatever is left over','Automate it from your paycheck','Keep cash under the mattress','Only save bonuses'], correct: 1 },
      { q: 'Saving $10/week for a year totals:', options: ['$120','$260','$520','$1,040'], correct: 2 },
      { q: 'Separate savings accounts for goals help because:', options: ['Banks require it','They earn more interest','They prevent you from mixing funds','The government mandates it'], correct: 2 },
      { q: 'When should you start saving?', options: ['When you have a high salary','After paying off all debt','Right now, even small amounts','After you turn 30'], correct: 2 },
      { q: 'Celebrating saving milestones helps:', options: ['Increase your debt','Reinforce the habit','Earn bonus interest','Avoid taxes'], correct: 1 },
    ],
  },
  {
    id: 'fees-and-costs', category: 'Banking', difficulty: 'beginner', emoji: '💸',
    title: 'Hidden Fees & Costs', xp: 10,
    description: 'The small charges that drain your account silently',
    content: 'Hidden fees quietly bleed your finances: monthly maintenance fees, ATM fees, overdraft fees ($35 per incident!), subscription auto-renewals, minimum balance fees, and foreign transaction fees. Audit your accounts quarterly. Most fees are negotiable or avoidable with the right account type.',
    questions: [
      { q: 'Average overdraft fee per incident:', options: ['$5','$15','$35','$50'], correct: 2 },
      { q: 'Which fee can you often avoid by switching banks?', options: ['Income tax','Monthly maintenance fee','Sales tax','Property tax'], correct: 1 },
      { q: 'How often should you audit your subscriptions?', options: ['Never','Once a decade','Every quarter','Only when broke'], correct: 2 },
      { q: 'Foreign transaction fees typically charge:', options: ['0%','1–3% per purchase','10%','Flat $50'], correct: 1 },
      { q: 'Best way to avoid ATM fees:', options: ['Never use ATMs','Use your bank\'s ATMs or get cash back at stores','Pay by check only','Use a credit card for cash'], correct: 1 },
    ],
  },
];

export const WORLD2_LESSONS = [
  {
    id: 'debt-types', category: 'Credit', difficulty: 'beginner', emoji: '🔗',
    title: 'Types of Debt', xp: 10,
    description: 'Not all debt is created equal',
    content: 'Secured debt is backed by collateral (mortgage = house, auto loan = car). If you default, they take the asset. Unsecured debt has no collateral — credit cards, student loans, personal loans. Interest rates are higher because the lender takes more risk. Good debt builds wealth (mortgage, student loans for high-ROI degrees). Bad debt destroys it (high-interest credit cards).',
    questions: [
      { q: 'A mortgage is an example of:', options: ['Unsecured debt','Secured debt','Good-faith credit','Revolving credit'], correct: 1 },
      { q: 'Unsecured debt typically has:', options: ['Lower interest rates','No interest','Higher interest rates','Collateral backing'], correct: 2 },
      { q: 'Credit card debt is:', options: ['Secured','Unsecured','Backed by your house','Regulated by FDIC'], correct: 1 },
      { q: '"Good" debt generally:', options: ['Has 0% interest','Funds assets that grow in value','Is government-issued only','Has no repayment period'], correct: 1 },
      { q: 'If you default on a secured loan:', options: ['Credit score improves','Lender can seize the collateral','You owe nothing','Government pays it'], correct: 1 },
    ],
  },
  {
    id: 'interest-rates-debt', category: 'Credit', difficulty: 'beginner', emoji: '📉',
    title: 'How Interest Rates Work', xp: 10,
    description: 'APR, APY, and why the numbers matter',
    content: 'APR (Annual Percentage Rate) is the yearly cost of borrowing including fees. APY (Annual Percentage Yield) reflects compound interest — it\'s what you actually earn or pay. Credit cards average 20–25% APR. Mortgages run 6–8%. The higher the rate, the more debt costs you. Even 1% less on a $200,000 mortgage saves ~$40,000 over 30 years.',
    questions: [
      { q: 'APR stands for:', options: ['Annual Profit Rate','Annual Percentage Rate','Adjusted Principal Rate','Accrued Payment Ratio'], correct: 1 },
      { q: 'Average credit card APR in the US:', options: ['5–8%','10–12%','20–25%','35–40%'], correct: 2 },
      { q: 'APY accounts for:', options: ['Fees only','Compound interest','Tax rates','Inflation only'], correct: 1 },
      { q: 'Lower APR on a loan means:', options: ['Less risk','You pay more total','You pay less total','Faster repayment'], correct: 2 },
      { q: 'Credit card minimum payment is dangerous because:', options: ['It hurts credit score','Interest accrues on remaining balance','Banks charge extra','Government taxes it'], correct: 1 },
    ],
  },
  {
    id: 'credit-card-debt', category: 'Credit', difficulty: 'beginner', emoji: '💳',
    title: 'Escaping Credit Card Debt', xp: 10,
    description: 'The most common and most dangerous debt for young people',
    content: 'Credit card debt at 20%+ APR is financial quicksand. A $5,000 balance paying only minimums takes 18+ years to repay and costs $7,000+ in interest. Strategies to escape: stop adding to the balance, pay more than the minimum, target the highest-rate card first (avalanche method), or call and negotiate a lower rate.',
    questions: [
      { q: '$5,000 credit card debt at 20% APR paying minimums = repaid in roughly:', options: ['1 year','5 years','10 years','18+ years'], correct: 3 },
      { q: 'First step to escape credit card debt:', options: ['Open a new card','Stop adding to the balance','Take out a personal loan','Ignore the statements'], correct: 1 },
      { q: 'Avalanche method means targeting:', options: ['Smallest balance first','Largest balance first','Highest interest rate first','Oldest debt first'], correct: 2 },
      { q: 'Calling your credit card company can get you:', options: ['Debt erased','A lower interest rate','Free rewards','A credit limit increase only'], correct: 1 },
      { q: 'Paying only the minimum payment means:', options: ['You\'ll be debt-free in 2 years','You mostly pay interest','Your score improves fast','No interest accumulates'], correct: 1 },
    ],
  },
  {
    id: 'student-loans', category: 'Credit', difficulty: 'intermediate', emoji: '🎓',
    title: 'Student Loan Basics', xp: 20,
    description: 'America\'s $1.7 trillion problem — understand yours',
    content: 'Federal student loans have fixed rates and income-driven repayment options. Private loans have variable rates and fewer protections. Subsidized federal loans don\'t accrue interest while in school. Unsubsidized do. Income-Driven Repayment (IDR) caps payments at 5–10% of your income. Public Service Loan Forgiveness (PSLF) cancels remaining balance after 10 years in public service.',
    questions: [
      { q: 'Federal student loans vs private:', options: ['Private have better protections','Federal have income-driven repayment options','Both are identical','Private have lower rates always'], correct: 1 },
      { q: 'Subsidized federal loans:', options: ['Accrue interest in school','Don\'t accrue interest while enrolled','Have higher rates','Require collateral'], correct: 1 },
      { q: 'PSLF forgives loans after how many years in public service?', options: ['5','10','20','25'], correct: 1 },
      { q: 'Income-Driven Repayment caps payments at:', options: ['0%','5–10% of income','25% of income','Fixed $500/month'], correct: 1 },
      { q: 'Refinancing federal loans into private ones means:', options: ['Lower rates guaranteed','You lose federal protections','PSLF eligibility increases','Interest stops accruing'], correct: 1 },
    ],
  },
  {
    id: 'debt-snowball-avalanche', category: 'Credit', difficulty: 'intermediate', emoji: '❄️',
    title: 'Snowball vs Avalanche Method', xp: 20,
    description: 'Two proven strategies to destroy your debt',
    content: 'Snowball: pay minimums on all debts, throw extra money at the smallest balance first. As each debt dies, roll that payment into the next. Psychologically motivating — quick wins keep you going. Avalanche: attack the highest interest rate first. Mathematically optimal — saves the most money. Choose based on whether you need motivation (snowball) or maximum savings (avalanche).',
    questions: [
      { q: 'Snowball method targets:', options: ['Highest rate first','Smallest balance first','Oldest debt first','Largest balance first'], correct: 1 },
      { q: 'Avalanche method is mathematically:', options: ['Worse than snowball','Equal to snowball','Better — saves more interest','Random'], correct: 2 },
      { q: '"Rolling" a payment means:', options: ['Paying late','Adding the paid-off debt\'s payment to the next debt','Refinancing','Paying minimum only'], correct: 1 },
      { q: 'Snowball\'s main advantage:', options: ['Maximum interest savings','Psychological quick wins','Lower monthly payments','Faster total payoff'], correct: 1 },
      { q: 'If you have a 25% APR and 5% APR debt, avalanche says:', options: ['Pay 5% APR first','Pay 25% APR first','Pay both equally','Ignore interest rates'], correct: 1 },
    ],
  },
  {
    id: 'credit-utilization', category: 'Credit', difficulty: 'intermediate', emoji: '📊',
    title: 'Credit Utilization', xp: 20,
    description: 'The credit score factor most people overlook',
    content: 'Credit utilization = your credit card balance ÷ your credit limit. If you have a $10,000 limit and owe $3,000, your utilization is 30%. Keeping it under 30% is good; under 10% is excellent. High utilization tanks your credit score fast — even if you pay on time. Ask for a credit limit increase or pay mid-cycle to lower your utilization.',
    questions: [
      { q: '$2,000 balance on a $10,000 limit = what utilization?', options: ['2%','10%','20%','50%'], correct: 2 },
      { q: 'Ideal credit utilization:', options: ['Under 80%','Under 50%','Under 30%','Exactly 0%'], correct: 2 },
      { q: 'Asking for a credit limit increase (without spending more) does what?', options: ['Increases utilization','Decreases utilization','Has no effect','Closes your account'], correct: 1 },
      { q: 'High utilization signals to lenders:', options: ['You\'re responsible','You may be overleveraged','You have good income','You are low-risk'], correct: 1 },
      { q: 'Paying your bill before the statement closing date:', options: ['Causes late fees','Reduces reported utilization','Increases your APR','Has no credit score effect'], correct: 1 },
    ],
  },
  {
    id: 'credit-report', category: 'Credit', difficulty: 'intermediate', emoji: '📋',
    title: 'Your Credit Report', xp: 20,
    description: 'The document that determines your financial life',
    content: 'Your credit report tracks your full credit history: every account, payment, missed payment, hard inquiry, and public record. Three bureaus — Equifax, Experian, TransUnion — each maintain a report. Check them free at AnnualCreditReport.com. Errors are common — dispute them immediately. 1 in 5 Americans has an error on their credit report.',
    questions: [
      { q: 'Three major credit bureaus are:', options: ['Chase, Wells, Citi','Equifax, Experian, TransUnion','FICO, VantageScore, Moody\'s','IRS, FTC, CFPB'], correct: 1 },
      { q: 'Free credit reports are available at:', options: ['CreditKarma.com only','Your bank app','AnnualCreditReport.com','The bank counter'], correct: 2 },
      { q: 'Errors on credit reports occur in roughly how many Americans?', options: ['1 in 100','1 in 20','1 in 5','1 in 2'], correct: 2 },
      { q: 'If you find an error, you should:', options: ['Ignore it','Dispute it with the bureau','Open a new account','Cut up your card'], correct: 1 },
      { q: 'How long do most negative items stay on your report?', options: ['1 year','3 years','7 years','Forever'], correct: 2 },
    ],
  },
  {
    id: 'hard-vs-soft-inquiry', category: 'Credit', difficulty: 'intermediate', emoji: '🔍',
    title: 'Hard vs Soft Inquiries', xp: 20,
    description: 'Not all credit checks are the same',
    content: 'A hard inquiry happens when a lender pulls your credit to make a lending decision — applying for a credit card, mortgage, or car loan. It can drop your score 5–10 points temporarily. Soft inquiries (checking your own score, employer background checks, pre-approval offers) do NOT affect your score at all. Rate shopping for a mortgage counts as one inquiry if done within 14–45 days.',
    questions: [
      { q: 'Hard inquiry examples include:', options: ['Checking your own score','Employer background check','Applying for a new credit card','Pre-approval offer'], correct: 2 },
      { q: 'Hard inquiries typically drop score by:', options: ['0 points','5–10 points','50–100 points','They improve score'], correct: 1 },
      { q: 'Soft inquiries affect your credit score by:', options: ['5 points','10 points','0 points','It depends'], correct: 2 },
      { q: 'Shopping mortgage rates within 14–45 days counts as:', options: ['Multiple hard inquiries','One hard inquiry','Multiple soft inquiries','No inquiry'], correct: 1 },
      { q: 'How long do hard inquiries stay on your report?', options: ['6 months','1 year','2 years','5 years'], correct: 2 },
    ],
  },
  {
    id: 'debt-consolidation', category: 'Credit', difficulty: 'intermediate', emoji: '🔄',
    title: 'Debt Consolidation', xp: 20,
    description: 'Combining debts into one — when it helps and when it hurts',
    content: 'Debt consolidation combines multiple debts into one loan, ideally at a lower interest rate. A personal loan at 12% to pay off cards at 22% saves money. Balance transfer cards offer 0% APR for 12–21 months — powerful if you can pay off the balance before the intro period ends. Warning: consolidation without fixing spending habits just delays the problem.',
    questions: [
      { q: 'Debt consolidation works best when:', options: ['New rate is higher than old','New rate is lower than old','You have one debt','You have perfect credit'], correct: 1 },
      { q: 'Balance transfer 0% APR is dangerous if:', options: ['You have no debt','You can\'t pay the balance before intro period ends','The limit is too high','You have a good score'], correct: 1 },
      { q: 'Consolidation without changing spending habits:', options: ['Solves the problem','Delays the problem','Erases the debt','Improves credit instantly'], correct: 1 },
      { q: 'Personal loan at 12% vs credit cards at 22% = annual savings on $10K:', options: ['$0','$500','$1,000','$3,000'], correct: 2 },
      { q: 'Balance transfer fees are typically:', options: ['0%','1–3% of amount transferred','10%','$500 flat'], correct: 1 },
    ],
  },
  {
    id: 'collections', category: 'Credit', difficulty: 'intermediate', emoji: '⚠️',
    title: 'Collections & Charge-Offs', xp: 20,
    description: 'What happens when debt goes unpaid',
    content: 'After ~90–180 days of missed payments, debt is charged off (the bank writes it off as a loss) and sold to a collection agency. The collection appears on your credit report and destroys your score. You still owe the money. You can negotiate a settlement (pay less than owed) or a "pay for delete" agreement. Collections stay on your report 7 years from the original delinquency.',
    questions: [
      { q: 'Debt typically goes to collections after how many missed days?', options: ['30 days','90–180 days','1 year','2 years'], correct: 1 },
      { q: 'A charge-off means:', options: ['The debt is forgiven','The bank wrote it off and may sell it to collectors','Your credit score improves','You get a tax break'], correct: 1 },
      { q: '"Pay for delete" means:', options: ['Paying and debt disappears legally','Creditor removes collection from report in exchange for payment','A type of bankruptcy','Government program'], correct: 1 },
      { q: 'How long do collections stay on your credit report?', options: ['1 year','3 years','7 years','Forever'], correct: 2 },
      { q: 'Settling a debt for less than owed means:', options: ['You avoid all consequences','The IRS may count forgiven amount as income','Your credit is restored immediately','Collectors cannot contact you again'], correct: 1 },
    ],
  },
  {
    id: 'building-credit-from-zero', category: 'Credit', difficulty: 'beginner', emoji: '🌱',
    title: 'Building Credit from Zero', xp: 10,
    description: 'No credit history? Here\'s how to start',
    content: 'With no credit, start with a secured credit card (you deposit $200–500 as collateral, which becomes your limit). Use it for small purchases and pay in full every month. After 6–12 months of on-time payments, you\'ll have a real credit score. Credit-builder loans at credit unions work the same way. Being added as an authorized user on someone\'s account also helps.',
    questions: [
      { q: 'A secured credit card requires:', options: ['A co-signer','A cash deposit as collateral','Perfect credit','A job offer letter'], correct: 1 },
      { q: 'With a secured card, you should:', options: ['Max it out','Pay in full every month','Never use it','Close it after one month'], correct: 1 },
      { q: 'When do you typically see a credit score appear?', options: ['Immediately','After 6 months of activity','After 5 years','Only with a bank account'], correct: 1 },
      { q: 'Being an authorized user on a parent\'s card:', options: ['Has no effect','Damages your score','Can help build your credit','Requires your own income'], correct: 2 },
      { q: 'A credit-builder loan works by:', options: ['Lending you money upfront','Holding payments in an account until loan is "paid"','Requiring collateral like a car','Government backing'], correct: 1 },
    ],
  },
  {
    id: 'bankruptcy-basics', category: 'Credit', difficulty: 'advanced', emoji: '🚨',
    title: 'Bankruptcy Basics', xp: 30,
    description: 'The nuclear option — when is it right?',
    content: 'Bankruptcy is a legal process that eliminates or restructures debts you can\'t repay. Chapter 7 liquidates assets and wipes most unsecured debt (takes ~4–6 months). Chapter 13 creates a 3–5 year repayment plan. Both destroy your credit for 7–10 years. Bankruptcy doesn\'t erase student loans, child support, or recent taxes. It\'s a last resort — explore all other options first.',
    questions: [
      { q: 'Chapter 7 bankruptcy:', options: ['Creates a repayment plan','Liquidates assets and wipes most unsecured debt','Only affects student loans','Improves credit score'], correct: 1 },
      { q: 'Chapter 13 bankruptcy involves:', options: ['Immediate debt erasure','A 3–5 year repayment plan','Only secured debt','Employer notification'], correct: 1 },
      { q: 'Bankruptcy stays on your credit report for:', options: ['1–2 years','5 years','7–10 years','Forever'], correct: 2 },
      { q: 'Which debt CANNOT be erased in bankruptcy?', options: ['Credit card debt','Medical bills','Student loans','Personal loans'], correct: 2 },
      { q: 'Bankruptcy should be considered:', options: ['As a first option','Only after all other options','For minor debts','To improve credit'], correct: 1 },
    ],
  },
];
