// World 3: Budgeting Mastery  |  World 4: Banking & Saving

export const WORLD3_LESSONS = [
  {
    id: 'zero-based-budgeting', category: 'Budgeting', difficulty: 'intermediate', emoji: '🎯',
    title: 'Zero-Based Budgeting', xp: 20,
    description: 'Every dollar gets a job — none left unassigned',
    content: 'Zero-based budgeting means income minus expenses equals zero — not because you spend it all, but because every dollar is assigned a purpose. Step 1: List income. Step 2: Assign every dollar to a category (including savings). Step 3: Leftover dollars go into savings or debt payoff. Apps like YNAB (You Need A Budget) automate this.',
    questions: [
      { q: 'Zero-based budget means income - expenses = ?', options: ['A big surplus','Zero (every dollar assigned)','A deficit','Your savings'], correct: 1 },
      { q: 'In ZBB, "leftover" money should:', options: ['Be spent on fun','Be assigned to savings or debt','Be kept in checking','Not exist'], correct: 1 },
      { q: 'ZBB requires you to:', options: ['Track spending after the fact','Assign every dollar before spending','Guess your expenses','Use only cash'], correct: 1 },
      { q: 'Which app is famous for zero-based budgeting?', options: ['Robinhood','YNAB (You Need A Budget)','Cash App','Venmo'], correct: 1 },
      { q: 'ZBB is most useful for people who:', options: ['Have unlimited income','Struggle with impulse spending','Already have no debt','Hate budgeting'], correct: 1 },
    ],
  },
  {
    id: 'envelope-method', category: 'Budgeting', difficulty: 'beginner', emoji: '✉️',
    title: 'The Envelope Method', xp: 10,
    description: 'Old-school cash budgeting that actually works',
    content: 'The envelope method: divide cash into labeled envelopes for each spending category (groceries, gas, entertainment). When an envelope is empty, stop spending in that category. It forces mindful spending because physical cash "feels" more real than a card swipe. Digital apps like Goodbudget replicate this virtually.',
    questions: [
      { q: 'The envelope method works best with:', options: ['Credit cards','Physical cash','Debit cards','Cryptocurrency'], correct: 1 },
      { q: 'When an envelope is empty:', options: ['Refill it from savings','Stop spending in that category','Borrow from another envelope','Open a new account'], correct: 1 },
      { q: 'Why does cash feel "more real" than cards?', options: ['Cash earns interest','Physical payment is more psychologically painful','Banks track it better','It has no fees'], correct: 1 },
      { q: 'Which app replicates the envelope method digitally?', options: ['Robinhood','Coinbase','Goodbudget','Bloomberg'], correct: 2 },
      { q: 'The envelope method is best for:', options: ['Long-term investing','Impulse spending control in specific categories','Stock market tracking','Credit score building'], correct: 1 },
    ],
  },
  {
    id: 'tracking-expenses', category: 'Budgeting', difficulty: 'beginner', emoji: '📱',
    title: 'Tracking Your Expenses', xp: 10,
    description: 'You can\'t manage what you don\'t measure',
    content: 'Expense tracking reveals where your money actually goes — often shocking vs where you think it goes. Methods: bank app spending categories, budgeting apps (Mint, Copilot), manual spreadsheet, or receipts. Track for 30 days before budgeting. Most people underestimate food/dining spending by 40–50%.',
    questions: [
      { q: 'Why track expenses before making a budget?', options: ['Banks require it','To see your actual spending patterns','For tax purposes','To qualify for loans'], correct: 1 },
      { q: 'Most people underestimate their spending on:', options: ['Rent','Utilities','Dining and food','Car payments'], correct: 2 },
      { q: 'How long should you track before budgeting?', options: ['One day','One week','30 days','One year'], correct: 2 },
      { q: 'Which is NOT an expense tracking method?', options: ['Bank app categories','Spreadsheet','Stock screener','Budgeting app'], correct: 2 },
      { q: 'Expense tracking works best when done:', options: ['Monthly in bulk','Consistently and in real-time','Only in December','Randomly'], correct: 1 },
    ],
  },
  {
    id: 'variable-vs-fixed', category: 'Budgeting', difficulty: 'beginner', emoji: '📊',
    title: 'Fixed vs Variable Expenses', xp: 10,
    description: 'Two types of expenses, two different strategies',
    content: 'Fixed expenses are the same every month: rent, car payment, insurance, subscriptions. Variable expenses change: groceries, gas, dining, entertainment. Fixed costs are easy to budget — they don\'t surprise you. Variable costs require tracking and caps. The easiest way to cut your budget fast: attack variable expenses first.',
    questions: [
      { q: 'Fixed expense example:', options: ['Groceries','Gas','Monthly rent','Restaurant meals'], correct: 2 },
      { q: 'Variable expense example:', options: ['Car payment','Insurance premium','Netflix subscription','Weekly grocery bill'], correct: 3 },
      { q: 'Fixed expenses are easy to budget because:', options: ['They are small','They don\'t change month to month','Banks set them','They are optional'], correct: 1 },
      { q: 'Fastest way to cut spending:', options: ['Lower fixed expenses first','Lower variable expenses first','Cut savings','Stop paying bills'], correct: 1 },
      { q: 'Which of these is semi-variable?', options: ['Rent','Electricity (base + usage)','Netflix','Car payment'], correct: 1 },
    ],
  },
  {
    id: 'subscription-audit', category: 'Budgeting', difficulty: 'beginner', emoji: '📺',
    title: 'Subscription Audit', xp: 10,
    description: 'Streaming, apps, and memberships are bleeding you dry',
    content: 'The average American spends $219/month on subscriptions — often without realizing it. Streaming services, gym memberships, app subscriptions, and trial periods add up fast. Audit: list every recurring charge from your bank statement. Cancel anything you haven\'t used in 30 days. The annual cost of $10/month subscriptions: $120 per service.',
    questions: [
      { q: 'Average American monthly subscription spending:', options: ['$50','$100','$219','$500'], correct: 2 },
      { q: 'Best way to find all your subscriptions:', options: ['Ask your friends','Check your bank/card statements','Call your bank','Check app store'], correct: 1 },
      { q: 'When should you cancel a subscription?', options: ['Never — it\'s convenient','If unused in 30+ days','Only at year end','When in debt only'], correct: 1 },
      { q: '$10/month subscription × 12 months = ?', options: ['$10','$60','$100','$120'], correct: 3 },
      { q: 'A "free trial" to watch out for:', options: ['Auto-renews without reminder','Provides full access','Is from the government','Has no cancellation'], correct: 0 },
    ],
  },
  {
    id: 'sinking-funds', category: 'Budgeting', difficulty: 'intermediate', emoji: '🪣',
    title: 'Sinking Funds', xp: 20,
    description: 'Never be surprised by a predictable expense again',
    content: 'A sinking fund is saving monthly for a known future expense. Car registration due in 6 months? Save 1/6 each month. Christmas gifts cost $600? Save $50/month. Annual insurance premiums, vacations, car repairs — all predictable costs that wreck budgets when treated as "surprises." Create separate savings buckets for each.',
    questions: [
      { q: 'A sinking fund is for:', options: ['Emergency unknowns','Known future expenses','Daily spending','Retirement'], correct: 1 },
      { q: '$600 Christmas budget saved over 12 months = ?/month', options: ['$25','$50','$100','$600'], correct: 1 },
      { q: 'Sinking funds prevent:', options: ['Investment losses','Budget-busting "surprise" expenses','Credit score drops','Inflation'], correct: 1 },
      { q: 'Best place to keep sinking funds:', options: ['Investment account','Separate savings sub-account','Your wallet','Mixed with emergency fund'], correct: 1 },
      { q: 'Which is a classic sinking fund category?', options: ['Random impulse buys','Car maintenance','Credit card bills','Tax refunds'], correct: 1 },
    ],
  },
  {
    id: 'anti-budget', category: 'Budgeting', difficulty: 'intermediate', emoji: '🔄',
    title: 'The Anti-Budget', xp: 20,
    description: 'For people who hate budgeting but still want results',
    content: 'The anti-budget: save first (automate savings/investments), pay fixed bills, then spend the rest guilt-free. No categories, no tracking, no stress. Also called the 80/20 method: save 20%, spend 80% however you want. Works if your savings rate is already good and you don\'t have high-interest debt.',
    questions: [
      { q: 'The anti-budget core principle:', options: ['Track every dollar','Save first, spend the rest freely','Never use credit cards','Budget 50/30/20 strictly'], correct: 1 },
      { q: 'Anti-budget works best when:', options: ['You have high-interest debt','Your savings rate is already healthy','You spend impulsively','You\'re in debt'], correct: 1 },
      { q: 'In the 80/20 anti-budget, 20% goes to:', options: ['Wants','Savings/investments','Dining out','Subscriptions'], correct: 1 },
      { q: 'The anti-budget still requires you to:', options: ['Track every purchase','Automate savings before spending','Use cash envelopes','Never eat out'], correct: 1 },
      { q: 'Who should NOT use the anti-budget?', options: ['High earners who already save','People who track expenses','People with high-interest debt and no savings','Minimalists'], correct: 2 },
    ],
  },
  {
    id: 'irregular-income', category: 'Budgeting', difficulty: 'intermediate', emoji: '📈',
    title: 'Budgeting with Irregular Income', xp: 20,
    description: 'Freelancers and gig workers: this is your guide',
    content: 'Irregular income requires a base budget: calculate your lowest monthly income over the past year and budget from that floor. Pay yourself a "salary" — transfer a fixed amount to checking for expenses and keep excess in savings. Set aside 25–30% for taxes immediately (quarterly estimated taxes). Build a 3–6 month income buffer.',
    questions: [
      { q: 'Base your irregular income budget on:', options: ['Your highest month','Your average month','Your lowest month','Last year\'s total'], correct: 2 },
      { q: 'Freelancers should set aside for taxes:', options: ['5–10%','15%','25–30%','40–50%'], correct: 2 },
      { q: '"Paying yourself a salary" means:', options: ['Working for free','Transferring fixed amount to checking regardless of income','Raising your rates','Working extra hours'], correct: 1 },
      { q: 'Recommended income buffer for freelancers:', options: ['1 month','3–6 months','1 year','No buffer needed'], correct: 1 },
      { q: 'Self-employed quarterly tax deadlines occur:', options: ['Once a year','Four times a year','Monthly','Every 2 years'], correct: 1 },
    ],
  },
  {
    id: 'food-budget', category: 'Budgeting', difficulty: 'beginner', emoji: '🍕',
    title: 'Mastering Your Food Budget', xp: 10,
    description: 'Food is the #1 place people overspend',
    content: 'The average American spends $400–800/month on food. Tactics to cut it: meal plan weekly, shop with a list, buy store brands (identical to name brands, 20–40% cheaper), batch cook on Sundays, use grocery apps for coupons, and reduce dining out to 1–2x/week. Cooking at home vs. ordering food: 60–80% cheaper per meal.',
    questions: [
      { q: 'Store brand vs name brand quality:', options: ['Name brands are always better','Store brands are often identical, just cheaper','Store brands are lower quality','Name brands are cheaper'], correct: 1 },
      { q: 'Cooking at home vs. ordering out is roughly:', options: ['Same cost','10–20% cheaper','60–80% cheaper','More expensive'], correct: 2 },
      { q: 'Best food budgeting habit:', options: ['Shop daily','Meal plan and shop with a list','Never buy in bulk','Avoid store brands'], correct: 1 },
      { q: 'Average American monthly food spend:', options: ['$100–200','$200–300','$400–800','$1,000–1,500'], correct: 2 },
      { q: 'Batch cooking on Sundays saves:', options: ['Time and money during the week','Only time','Only money','Nothing'], correct: 0 },
    ],
  },
  {
    id: 'budget-categories', category: 'Budgeting', difficulty: 'beginner', emoji: '🗂️',
    title: 'Budget Categories That Work', xp: 10,
    description: 'How to slice your budget pie',
    content: 'Essential categories: Housing (rent/mortgage), Transportation, Groceries, Utilities, Insurance, Debt payments, Savings/investments. Lifestyle categories: Dining out, Entertainment, Clothing, Personal care. One-time categories: Gifts, Travel, Medical. A good budget has 10–15 categories — too few and you lose visibility; too many and you lose motivation.',
    questions: [
      { q: 'Housing should ideally be under what % of income?', options: ['20%','30%','50%','70%'], correct: 1 },
      { q: 'How many budget categories is typically ideal?', options: ['2–3','5–6','10–15','30+'], correct: 2 },
      { q: '"Debt payments" belongs in which budget type?', options: ['Lifestyle','Essential','One-time','Savings'], correct: 1 },
      { q: 'A gift budget is a type of:', options: ['Fixed expense','Variable essential','One-time/irregular','Housing'], correct: 2 },
      { q: 'Savings should appear in your budget as:', options: ['Leftover money','A non-negotiable category','Optional if possible','Zero'], correct: 1 },
    ],
  },
  {
    id: 'lifestyle-creep-budget', category: 'Budgeting', difficulty: 'intermediate', emoji: '📈',
    title: 'Fighting Lifestyle Creep', xp: 20,
    description: 'Why raises never seem to be enough',
    content: 'Lifestyle creep (lifestyle inflation) happens when spending rises with income — new car, bigger apartment, fancier restaurants. The result: no matter how much you earn, you feel broke. The antidote: when income increases, direct 50%+ of the raise to savings/investments and let only a fraction raise your lifestyle. Your savings rate matters more than your income.',
    questions: [
      { q: 'Lifestyle creep means:', options: ['Spending decreases with income','Spending rises with income','Saving more as you earn more','Investing in real estate'], correct: 1 },
      { q: 'When you get a raise, best practice:', options: ['Upgrade your lifestyle fully','Save 50%+ of the raise, lifestyle up the rest','Spend it all — you earned it','Ignore it'], correct: 1 },
      { q: 'What determines wealth more than income?', options: ['Salary','Job title','Savings rate','Location'], correct: 2 },
      { q: 'Someone earning $200K can still be broke due to:', options: ['Taxes only','Lifestyle creep','Bad luck','Inflation'], correct: 1 },
      { q: 'Hedonic adaptation means:', options: ['You adapt to and stop appreciating upgrades','You always want less','Your savings grow automatically','Your income rises with inflation'], correct: 0 },
    ],
  },
  {
    id: 'budgeting-apps', category: 'Budgeting', difficulty: 'beginner', emoji: '📱',
    title: 'Budgeting Apps Compared', xp: 10,
    description: 'The right tool makes budgeting painless',
    content: 'Popular budgeting apps: YNAB (proactive, zero-based, $14/month) — best for people serious about budgeting. Mint (free, auto-categorizes) — good starter. Copilot (iOS, AI-powered, $13/month) — beautiful and smart. Personal Capital (net worth focus, free) — best for investors. The best app is the one you actually use consistently.',
    questions: [
      { q: 'YNAB\'s budgeting philosophy:', options: ['Spend freely','Zero-based — assign every dollar','Track after spending','Invest everything'], correct: 1 },
      { q: 'Best free budgeting app for beginners:', options: ['Bloomberg Terminal','Mint','Robinhood','TD Ameritrade'], correct: 1 },
      { q: 'Personal Capital is best for tracking:', options: ['Grocery spending','Daily habits','Net worth and investments','Social spending'], correct: 2 },
      { q: 'The best budgeting app is:', options: ['The most expensive one','The one you actually use consistently','YNAB always','Whatever your friend uses'], correct: 1 },
      { q: 'Budgeting apps connect to your accounts to:', options: ['Invest your money','Auto-track and categorize spending','Replace your bank','Pay your bills'], correct: 1 },
    ],
  },
];

export const WORLD4_LESSONS = [
  {
    id: 'fdic-insurance', category: 'Banking', difficulty: 'beginner', emoji: '🛡️',
    title: 'FDIC Insurance', xp: 10,
    description: 'Why your bank deposits are (mostly) safe',
    content: 'FDIC insurance protects your bank deposits up to $250,000 per depositor, per bank, per account category. If your bank fails, the government guarantees your money up to that limit. Credit unions have equivalent protection through NCUA. Keep accounts under $250K per bank or spread across banks to stay fully protected.',
    questions: [
      { q: 'FDIC insures bank deposits up to:', options: ['$50,000','$100,000','$250,000','$1,000,000'], correct: 2 },
      { q: 'If your FDIC-insured bank fails:', options: ['You lose all your money','Government covers up to $250K','Nothing happens','Interest stops'], correct: 1 },
      { q: 'Credit union equivalent of FDIC:', options: ['SEC','NCUA','FINRA','OCC'], correct: 1 },
      { q: 'If you have $400K in one bank, FDIC covers:', options: ['All of it','$250K','$400K','Nothing'], correct: 1 },
      { q: 'To protect over $250K, you should:', options: ['Invest it in stocks','Spread across multiple banks','Withdraw it all','Keep it in crypto'], correct: 1 },
    ],
  },
  {
    id: 'hysa', category: 'Banking', difficulty: 'beginner', emoji: '💹',
    title: 'High-Yield Savings Accounts', xp: 10,
    description: 'Make your savings work harder for free',
    content: 'A high-yield savings account (HYSA) pays 4–5% APY (2025 rates) vs 0.01% at traditional banks. Online banks (Marcus, Ally, SoFi, Discover) offer the best rates because they have no physical branches. Keep 3–6 months expenses here. $10,000 in a 5% HYSA vs 0.01% HYSA = $499 vs $1 difference per year.',
    questions: [
      { q: 'HYSA rates in 2025 can reach:', options: ['0.01%','0.5%','4–5%','15%'], correct: 2 },
      { q: 'Why do online banks offer better HYSA rates?', options: ['They take more risk','No physical branch overhead','Government subsidies','They have more customers'], correct: 1 },
      { q: '$10,000 at 5% APY earns annually:', options: ['$50','$100','$500','$5,000'], correct: 2 },
      { q: 'Best use of a HYSA:', options: ['Day trading','Emergency fund and short-term savings','Long-term retirement','Checking account replacement'], correct: 1 },
      { q: 'Traditional big bank savings rate is typically:', options: ['5%','2%','0.01%–0.05%','10%'], correct: 2 },
    ],
  },
  {
    id: 'cds', category: 'Banking', difficulty: 'intermediate', emoji: '🔒',
    title: 'Certificates of Deposit (CDs)', xp: 20,
    description: 'Lock your money in, earn a guaranteed rate',
    content: 'A CD locks your money for a set term (3 months to 5 years) at a fixed interest rate, often higher than HYSAs. Withdraw early and you pay a penalty (usually 3–6 months of interest). CD laddering: spread money across multiple CDs with different maturities, so you have access to funds regularly while still earning higher rates.',
    questions: [
      { q: 'CDs pay a higher rate because:', options: ['They are riskier','You lock money for a set term','They are government bonds','Banks prefer them'], correct: 1 },
      { q: 'Early withdrawal penalty on a CD is typically:', options: ['No penalty','3–6 months interest','$500 flat','50% of balance'], correct: 1 },
      { q: 'CD laddering means:', options: ['Buying one long-term CD','Spreading money across multiple CDs with different maturities','Investing in bond ETFs','A banking strategy for loans'], correct: 1 },
      { q: 'CDs are best when you:', options: ['Need daily access to funds','Won\'t need the money for the term','Are day trading','Have credit card debt'], correct: 1 },
      { q: 'CD interest is:', options: ['Tax-free','Taxed as ordinary income','Only taxed on withdrawal','Not reported to IRS'], correct: 1 },
    ],
  },
  {
    id: 'overdraft', category: 'Banking', difficulty: 'beginner', emoji: '⚠️',
    title: 'Overdraft Fees & Protection', xp: 10,
    description: 'The most avoidable fee in banking',
    content: 'Overdraft happens when you spend more than your account balance. Banks charge $35/overdraft (some banks charge $35 multiple times in a day). Protection options: opt into overdraft coverage (bank covers and charges you), link a savings account (free transfer), or use a bank with no overdraft fees (Chime, Current, SoFi). Better option: keep a $200+ buffer in checking.',
    questions: [
      { q: 'Average overdraft fee:', options: ['$5','$15','$35','$100'], correct: 2 },
      { q: 'Best way to avoid overdraft fees:', options: ['Opt into overdraft coverage','Keep a buffer in checking / use no-fee bank','Never use your debit card','Only use credit cards'], correct: 1 },
      { q: 'Which bank type often has no overdraft fees?', options: ['Big traditional banks','Credit card companies','Online/neobanks (Chime, SoFi)','Investment brokerages'], correct: 2 },
      { q: 'Linking a savings account for overdraft protection:', options: ['Costs $35 per transfer','Is usually free or low-cost','Damages your credit','Is not allowed'], correct: 1 },
      { q: 'A "buffer" in your checking account means:', options: ['Overdraft protection','Extra cash above your expenses as a cushion','A CD product','A loan'], correct: 1 },
    ],
  },
  {
    id: 'money-market', category: 'Banking', difficulty: 'intermediate', emoji: '🏦',
    title: 'Money Market Accounts', xp: 20,
    description: 'The hybrid between checking and savings',
    content: 'Money market accounts (MMAs) earn higher interest than regular savings (similar to HYSAs) and offer limited check-writing or debit card access. Higher minimum balance requirements ($1,000–$10,000). FDIC insured. Different from money market funds (which are investment products, not bank accounts, and not FDIC insured).',
    questions: [
      { q: 'MMAs offer higher interest AND:', options: ['Stock market exposure','Limited check writing or debit access','No FDIC insurance','Unlimited withdrawals'], correct: 1 },
      { q: 'MMA vs regular savings account:', options: ['MMA always pays less','MMA usually pays more with higher minimums','They\'re identical','MMA has no fees'], correct: 1 },
      { q: 'Money market ACCOUNT (bank) vs money market FUND (investment):', options: ['Identical products','Account is FDIC insured; Fund is not','Fund is safer','Account earns more'], correct: 1 },
      { q: 'Typical MMA minimum balance:', options: ['$1','$100','$1,000–$10,000','$50,000'], correct: 2 },
      { q: 'Best use of a money market account:', options: ['Daily transactions','Emergency fund or large short-term savings','Long-term retirement','High-risk trading'], correct: 1 },
    ],
  },
  {
    id: 'automatic-savings', category: 'Banking', difficulty: 'beginner', emoji: '🤖',
    title: 'Automating Your Savings', xp: 10,
    description: 'Remove willpower from the equation entirely',
    content: 'Automation removes the decision to save. Set up automatic transfers from checking to savings on payday. You never see the money, so you don\'t miss it. Apps like Qapital round up purchases and save the difference. Digit analyzes spending and auto-saves small amounts. Goal: have your savings happen without a single monthly decision from you.',
    questions: [
      { q: 'Automating savings works because:', options: ['Banks pay you to do it','You save without needing willpower','It earns higher interest','It improves credit score'], correct: 1 },
      { q: 'Best time to schedule an auto-transfer to savings:', options: ['End of month','The day after payday','Randomly','When you feel like it'], correct: 1 },
      { q: 'Apps like Qapital save money by:', options: ['Investing in stocks','Rounding up purchases and saving the difference','Cutting subscriptions','Tracking credit score'], correct: 1 },
      { q: 'The goal of savings automation:', options: ['Save only when convenient','Eliminate monthly savings decisions entirely','Invest in real estate','Pay down debt'], correct: 1 },
      { q: '"Set it and forget it" savings means:', options: ['Ignore your finances','Automate consistently and check occasionally','Never save','Invest automatically in stocks'], correct: 1 },
    ],
  },
  {
    id: 'direct-deposit', category: 'Banking', difficulty: 'beginner', emoji: '💸',
    title: 'Direct Deposit Perks', xp: 10,
    description: 'Get paid faster and unlock hidden banking benefits',
    content: 'Direct deposit sends your paycheck electronically to your bank, usually 1–2 days faster than a paper check. Many banks waive monthly fees if you have direct deposit. Online banks often give early direct deposit (2 days early). Some banks give cash bonuses ($200–$400) for setting up direct deposit. Always set up direct deposit — no downside.',
    questions: [
      { q: 'Direct deposit arrives how much faster than a check?', options: ['Same day','1–2 days faster','1 week faster','Same speed'], correct: 1 },
      { q: 'Many banks waive monthly fees if you:', options: ['Keep $10,000 minimum','Set up direct deposit','Use a credit card','Have 5 accounts'], correct: 1 },
      { q: 'Early direct deposit means you can get paid up to:', options: ['1 day late','2 days early','1 week early','Same day'], correct: 1 },
      { q: 'Direct deposit bonuses from banks can be:', options: ['$5–10','$50–100','$200–400','$5,000'], correct: 2 },
      { q: 'What is a downside of direct deposit?', options: ['Slower payment','Higher taxes','Fewer bank benefits','No downsides'], correct: 3 },
    ],
  },
  {
    id: 'mobile-banking-security', category: 'Banking', difficulty: 'intermediate', emoji: '🔐',
    title: 'Mobile Banking Security', xp: 20,
    description: 'Protect your money in the digital age',
    content: 'Mobile banking security essentials: use strong unique passwords + a password manager, enable two-factor authentication (2FA), never bank on public Wi-Fi (use VPN), freeze your credit (free, prevents new accounts being opened in your name), monitor accounts weekly, and know how to report fraud immediately.',
    questions: [
      { q: 'Two-factor authentication (2FA) adds security by:', options: ['Doubling your password length','Requiring a second verification step','Encrypting your card','Freezing your account'], correct: 1 },
      { q: 'Banking on public Wi-Fi is risky because:', options: ['It\'s slower','Hackers can intercept data on unsecured networks','Banks block it','Your balance is shown to others'], correct: 1 },
      { q: 'Freezing your credit prevents:', options: ['All spending','New credit accounts being opened in your name','Existing accounts being hacked','Investment losses'], correct: 1 },
      { q: 'Freezing credit is:', options: ['Expensive','Free and reversible','Permanent','Only for fraud victims'], correct: 1 },
      { q: 'If you notice suspicious banking activity:', options: ['Wait and see','Report immediately to your bank','Post on social media','Contact the IRS'], correct: 1 },
    ],
  },
  {
    id: 'banking-alternatives', category: 'Banking', difficulty: 'intermediate', emoji: '🌐',
    title: 'Banking Alternatives', xp: 20,
    description: 'Traditional banks aren\'t your only option',
    content: 'Alternatives to big banks: Credit unions (nonprofit, member-owned, better rates, local). Online banks (Ally, Marcus, Discover — higher HYSA rates, no physical branch). Neobanks (Chime, Current, SoFi — tech-first, no fees, early paycheck). Each has trade-offs: credit unions need membership, online banks lack ATMs, neobanks may have deposit limits.',
    questions: [
      { q: 'Credit unions differ from banks because they are:', options: ['Government-owned','For-profit corporations','Nonprofit, member-owned','Only for businesses'], correct: 2 },
      { q: 'Online banks like Ally/Marcus offer:', options: ['More ATMs than traditional banks','Higher savings rates due to lower overhead','Physical branch access','Lower FDIC limits'], correct: 1 },
      { q: 'Neobanks (Chime, SoFi) are best known for:', options: ['Physical branches','Stock trading','No-fee accounts with early paycheck','CD accounts'], correct: 2 },
      { q: 'Main downside of online-only banks:', options: ['Lower interest rates','No FDIC insurance','Limited ATM access and no branches','Higher fees'], correct: 2 },
      { q: 'To join a credit union you typically need to:', options: ['Have perfect credit','Meet membership criteria (employer, community)','Invest $10,000','Have a cosigner'], correct: 1 },
    ],
  },
  {
    id: 'savings-rate', category: 'Banking', difficulty: 'intermediate', emoji: '📊',
    title: 'Your Savings Rate', xp: 20,
    description: 'The single most important number in personal finance',
    content: 'Savings rate = (money saved / income) × 100. A 10% savings rate is the American average. 15–20% is recommended for a comfortable retirement. 50%+ leads to financial independence in 15–20 years. Doubling your savings rate from 10% to 20% cuts your retirement timeline nearly in half. Income matters less than your savings rate for building wealth.',
    questions: [
      { q: 'Savings rate formula:', options: ['Income / savings','Savings / income × 100','Expenses / income','Debt / savings'], correct: 1 },
      { q: 'Recommended minimum savings rate for retirement:', options: ['5%','10%','15–20%','50%'], correct: 2 },
      { q: 'A 50%+ savings rate can lead to financial independence in:', options: ['5 years','15–20 years','30–40 years','Never'], correct: 1 },
      { q: 'Going from 10% to 20% savings rate roughly:', options: ['Has no effect','Halves your retirement timeline','Doubles your timeline','Adds 5 years'], correct: 1 },
      { q: 'Income or savings rate — which matters more for wealth?', options: ['Income always dominates','Savings rate is the bigger factor','They\'re equally important','Neither matters, only investing'], correct: 1 },
    ],
  },
  {
    id: 'wire-transfers', category: 'Banking', difficulty: 'intermediate', emoji: '🔁',
    title: 'Wire Transfers & ACH', xp: 20,
    description: 'Moving money between banks — know the difference',
    content: 'Wire transfers move money bank-to-bank same day or next day. Domestic wires cost $15–35. International wires: $25–50+. ACH (Automated Clearing House) transfers are slower (1–3 days) but FREE — used for bill pay, payroll, and personal transfers. Zelle uses the ACH network but is near-instant between enrolled banks. Wire fraud is irreversible — verify all wire instructions.',
    questions: [
      { q: 'Wire transfers vs ACH: wire transfers are:', options: ['Slower but free','Faster but cost $15–50','Always free','Illegal for individuals'], correct: 1 },
      { q: 'ACH transfers typically take:', options: ['Seconds','1–3 business days','1 week','Same day always'], correct: 1 },
      { q: 'Zelle uses what network?', options: ['Wire network','ACH network (near-instant)','Crypto blockchain','Visa network'], correct: 1 },
      { q: 'Wire fraud is dangerous because:', options: ['Banks charge extra','It\'s reversible easily','It\'s nearly impossible to reverse','The government covers losses'], correct: 2 },
      { q: 'Average domestic wire transfer fee:', options: ['Free','$1–5','$15–35','$100+'], correct: 2 },
    ],
  },
  {
    id: 'checking-account-fees', category: 'Banking', difficulty: 'beginner', emoji: '🏦',
    title: 'Avoiding Checking Account Fees', xp: 10,
    description: 'Big banks charge for the privilege of keeping your money',
    content: 'Common checking fees: monthly maintenance ($5–25), minimum balance, out-of-network ATM, paper statement, overdraft, foreign transaction. How to avoid them: choose a bank with no monthly fee (most online banks and credit unions), maintain minimum balance, set up direct deposit, use in-network ATMs, go paperless. The right account has $0 in fees.',
    questions: [
      { q: 'Monthly checking maintenance fees range from:', options: ['Free–$5','$5–25','$50–100','$200+'], correct: 1 },
      { q: 'Most common way to waive a monthly fee:', options: ['Having 5+ accounts','Setting up direct deposit or maintaining minimum balance','Using the card daily','Calling monthly'], correct: 1 },
      { q: 'Online banks and credit unions typically charge:', options: ['Higher fees than big banks','The same fees','Zero or very low fees','Only ATM fees'], correct: 2 },
      { q: 'Going paperless on your account:', options: ['Adds a fee','Usually waives a paper statement fee','Has no effect','Reduces interest rate'], correct: 1 },
      { q: 'Out-of-network ATM fees can reach:', options: ['$0','$1','$3–6 combined (your bank + ATM owner)','$25'], correct: 2 },
    ],
  },
];
